### ISSUE TITLE
Allow option to auto continue main thread breakpoints

### ISSUE THREAD

**Issue by triwav** [TwitchBronBron/vscode-brightscript-language#120]
If you add a breakpoint most of the time when you resume the main thread run loop will continue trying to break. You can hit continue several times to try and get back going and that's what this issue would attempt to do. The ideal would be have Roku address this but it's uncertain when or if that will happen. One suggestion is a popup that would show up when this situation is addressed with the following. 
1. yes, do that (this session)
2. yes do that (always)
3. Don't ask again (for this session)
4. Don't ask again (ever)
5. [just ignore the box] (edited)
This seems fine to me but am open to other options.

**Comment by georgejecook** [comment]
I like this idea - I don't think it will work (in my experience it will crash, if you have tasks, which any reasonable sized project will have); but hell - it's a smart workaround for now, should it work

**Comment by TwitchBronBron** [comment]
@triwav was this resolved by the fixes that @georgejecook added to the debugger in #129?

**Comment by TwitchBronBron** [comment]
@triwav just checking in again, is this resolved?

**Comment by triwav** [comment]
This still happens at least for me. @georgejecook I think you did some work on something similar to this what was your thoughts on this?
