### ISSUE TITLE
debug output in console must be searchable

### ISSUE THREAD

**Issue by georgejecook** [TwitchBronBron/vscode-brightscript-language#15]
Search/find doesn't work on console output, currently.

This issue suggests redirecting to terminal, which doesn't work.

https://github.com/Microsoft/vscode/issues/4338

I'm not sure what the solution would be in this case; but it's really painful to not be able to search. I'm not sure how hard it is to have a custom component for all of the telnet output..

**Comment by georgejecook** [comment]
can you assign this to me @TwitchBronBron ? I've already implemented this and have a PR waiting for you.

**Comment by georgejecook** [comment]
This is resolved

**Comment by stevedekorte** [comment]
I'm still not able to search the debug console on VS 1.40.2 on OSX. Am I missing something?

**Comment by TwitchBronBron** [comment]
Yeah, we basically abandoned the debug console. lol. We pipe all of the output into an Output panel in vscode named "BrightScript Log". The output panels are much more flexible. Give that a try. :)

![image](https://user-images.githubusercontent.com/2544493/70189767-2a750500-16c2-11ea-8364-422ae30a08c9.png)
